[tool.poetry]
name = "wsdl-inline-imports"
version = "0.1.0"
description = ""
authors = ["Giovanni Berti <giovanni.berti@pagopa.it>"]

[tool.poetry.dependencies]
python = "^3.10"
lxml = "^4.7.1"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
